// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: b.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from b.proto</summary>
public static partial class BReflection {

  #region Descriptor
  /// <summary>File descriptor for b.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static BReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "CgdiLnByb3RvIi8KCFJlc3BvbnNlEhAKCHJlc190eXBlGAEgASgEEhEKCXJl",
          "c190eXBlMhgCIAEoBGIGcHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::Response), global::Response.Parser, new[]{ "ResType", "ResType2" }, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class Response : pb::IMessage<Response> {
  private static readonly pb::MessageParser<Response> _parser = new pb::MessageParser<Response>(() => new Response());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<Response> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::BReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Response() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Response(Response other) : this() {
    resType_ = other.resType_;
    resType2_ = other.resType2_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Response Clone() {
    return new Response(this);
  }

  /// <summary>Field number for the "res_type" field.</summary>
  public const int ResTypeFieldNumber = 1;
  private ulong resType_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ulong ResType {
    get { return resType_; }
    set {
      resType_ = value;
    }
  }

  /// <summary>Field number for the "res_type2" field.</summary>
  public const int ResType2FieldNumber = 2;
  private ulong resType2_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ulong ResType2 {
    get { return resType2_; }
    set {
      resType2_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as Response);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(Response other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (ResType != other.ResType) return false;
    if (ResType2 != other.ResType2) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (ResType != 0UL) hash ^= ResType.GetHashCode();
    if (ResType2 != 0UL) hash ^= ResType2.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (ResType != 0UL) {
      output.WriteRawTag(8);
      output.WriteUInt64(ResType);
    }
    if (ResType2 != 0UL) {
      output.WriteRawTag(16);
      output.WriteUInt64(ResType2);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (ResType != 0UL) {
      size += 1 + pb::CodedOutputStream.ComputeUInt64Size(ResType);
    }
    if (ResType2 != 0UL) {
      size += 1 + pb::CodedOutputStream.ComputeUInt64Size(ResType2);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(Response other) {
    if (other == null) {
      return;
    }
    if (other.ResType != 0UL) {
      ResType = other.ResType;
    }
    if (other.ResType2 != 0UL) {
      ResType2 = other.ResType2;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          ResType = input.ReadUInt64();
          break;
        }
        case 16: {
          ResType2 = input.ReadUInt64();
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
